package:
  name: pscache
  version: "0.2"

source:
  git_url: https://github.com/lcls-psana/pscache
  git_tag: "v0.2"

build:
  number: 3
  script:
    - pip install --no-deps --disable-pip-version-check .

requirements:
  build:
    - python
    - setuptools
    - redis-py
    - numpy
    - psana-conda

  run:
    - python
    - redis-py
    - numpy
    - psana-conda

about:
  home: https://github.com/lcls-psana/pscache

