{% set pkg = 'tables' %}
{% set version = '3.3.0' %}
{% set build = 102 %}

package:
  name: {{ pkg }}
  version: {{ version }}

source:
  # this came from github, not pypi
  fn: /reg/g/psdm/sw/conda/downloads/otherpkgs/{{ pkg }}-{{ version }}.tar.gz

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy
    - zlib 1.2.*
    - lzo 2.06  # [linux]
    - bzip2 1.0.*
    - hdf5 ==1.8.18 openmpi_2
    - openmpi ==2.0.2 lsf_verbs_1
    - numexpr
  run:
    - python
    - six
    - numpy
    - numexpr
    - hdf5 1.8.18
    - zlib 1.2.*
    - bzip2 1.0.*  # [win]

test:
  requires:
    - setuptools
  commands:
    - pt2to3 -h
    - ptdump -h
    - ptrepack -h
    - pttree -h

build:
  number: {{build}}
  string: py27_{{build}}

