{% set build = 1 %}

package:
  name: kafka-python
  version: "1.3.3"

build:
  number: {{build}}
  string: py{{py}}_{{build}}


requirements:
  build:
    - python ==3.5
    - pip
    - wheel
    - setuptools

  run:
    - python >=3.5,<4
  

