package:
  name: ndarray
  version: 1.1.8

source:
  git_url: https://github.com/lcls-psana/ndarray.git
  git_rev: V01-01-08

build:
  number: 0

requirements:
  build:
    - boost
  run:
    - boost

