package:
  name: psocake
  version: "0.2"

source:
  git_url: https://github.com/lcls-psana/psocake
  git_tag: "v0.2.3"

build:
  number: 2
  script:
    - pip install --no-deps --disable-pip-version-check .

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - scipy
    - pandas
    - pyqtgraph
    - h5py
    - scikit-learn
    - mpi4py
    - scikit-image


