package:
  name: peaknet
  version: '{{ environ.get("GIT_DESCRIBE_TAG", "0.0.0") }}'

source:
  git_url: https://github.com/lcls-psana/peaknet.git

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script:
    - pip install --no-deps --disable-pip-version-check .

requirements:
  build:
    - python
    - setuptools

  # we also need pytorch, cudatoolkit, torchvision, cudnn, but in the past
  # we have installed these using the command from pytorch.org.
  # cudnn needs to match cudatoolkit version.
  # because of this complexity we will leave out these dependencies here.
  run:
    - python
    - numpy
