package:
  name: logbookclient
  version: "0.0.5"

source:
  git_url: https://github.com/slaclab/LogBookClient.git
  git_tag: "0.0.5"

build:
  script:
    - pip install --no-deps --disable-pip-version-check .

requirements:
  build:
    - python
    - setuptools
    - requests
    - simplejson
    - mysql-python
    - qt
  run:
    - python
    - requests
    - simplejson
    - mysql-python
    - qt

about:
  home: https://github.com/slaclab/LogBookClient
  license: EPICS

