{% set build = 101 %}
{% set version = '2.5.0' %}
{% set mpi = 'openmpi' %}

package:
  name: h5py
  version: {{version}}

source:
  fn: /reg/g/psdm/sw/conda/downloads/otherpkgs/h5py-{{version}}.tar.gz
  patches:
    - modify_h5py_2.5.0_to_use_mpi4py_2.0.0.patch

requirements:
  build:
    - python
    - numpy
    - openmpi ==1.10.3 lsf_verbs_101
    - mpi4py ==2.0.0 py27_openmpi_101
    - hdf5 ==1.8.17 openmpi_101
    - cython
    - six
    - pkgconfig

  run:
    - python >=2.7,<3
    - numpy >=1.11,<1.12
    - openmpi >=1.8,<2
    - mpi4py >=2.0.0,<3
    - hdf5 ==1.8.17
    - six
    - unittest2    #[py26]

build:
  number: {{build}}
  string: py27_{{build}}

