{% set pkg = 'psana-conda' %}
{% set version = '2.0.95' %}
{% set build = 0 %}

package:
  name: {{ pkg }}
  version: {{ version }}

source:
  url: file:///root/anarel-manage/downloads/anarel/{{ pkg }}-{{ version }}.tar.gz

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
    - make
    - python
    - scons
  host:
    - scons
    - xorg-libxfixes  # [linux]
    - python
    - cython
    - boost=1.70.0
    - mysql=5.7.20
    - ndarray
    - qt
    - scipy
    - mpi4py
    - h5py
    - pytables
    - future
    - six
    - curl
    - libtiff

  run:
    - python
    - scons
    - cython
    - boost=1.70.0
    - mysql=5.7.20
    - mysqlclient
    - ndarray
    - qt
    - numpy
    - matplotlib
    - scipy
    - pyzmq
    - h5py
    - mpi4py
    - pytables
    - future
    - six
    - curl
    - libtiff

build:
  number: {{ build }}
  string: py{{py}}_{{ build }}

  script_env:
    - SIT_ARCH
    - SIT_ROOT

test:
  commands:
    - psana -h
