package:
  name: hdf5
  version: 1.8.16

source:
  fn: /reg/g/psdm/sw/conda/downloads/otherpkgs/hdf5-1.8.16.tar.gz
  patches:
    - shuffle.patch 
    - cachesize.patch

requirements:
  build:
    - szip >=2.1
    - openmpi >=1.8.6

  run:
    - szip >=2.1
    - openmpi >=1.8.6

build:
  number: 2
  binary_relocation: true
  detect_binary_files_with_prefix: true

