{% set pkg = 'hdf5' %}
{% set version = '1.8.17' %}
{% set build = 101 %}

package:
  name: {{ pkg }}
  version: {{ version }}

about:
  home: https://www.hdfgroup.org/HDF5
  summary: 'hdf5 data model, library and file format for storing and managing data'
  license: 'BSD style (https://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.0/src/unpacked/COPYING)'

source:
  fn: /reg/g/psdm/sw/conda/downloads/otherpkgs/{{ pkg }}-{{ version }}.tar.gz
#  url: http://www.hdfgroup.org/ftp/HDF5/current/src/{{ pkg }}-{{ version }}.tar.gz
  md5: 7d572f8f3b798a628b8245af0391a0ca
  patches:
    - cachesize.patch

requirements:
  build:
    - szip ==2.1
    - openmpi ==1.10.3 lsf_verbs_101

  run:
    - szip ==2.1
    - openmpi >=1.8,<2

build:
  number: {{ build }}
  string: openmpi_{{ build }}
  binary_relocation: true
  detect_binary_files_with_prefix: true

