{% set pkg = 'tables' %}
{% set version = '3.3.0' %}
{% set build = 101 %}

package:
  name: {{ pkg }}
  version: {{ version }}

about:
  home: https://github.com/PyTables/PyTables/releases/tag/v3.3.0
  summary: 'Hierarchical datasets for Python.'
  license: 'BSD License'

source:
  fn: /reg/g/psdm/sw/conda/downloads/otherpkgs/{{ pkg }}-{{ version }}.tar.gz
  md5: 056c161ae0fd2d6e585b766adacf3b0b

requirements:
  build:
  - python
  - setuptools
  - cython
  - numpy
  - zlib 1.2.*
  - lzo 2.06  # [linux]
  - bzip2 1.0.*
  - hdf5 ==1.8.18 openmpi_1
  - openmpi ==2.0.1 lsf_verbs_1
  - numexpr

  run:
  - python >=3.5,<4
  - six
  - numpy
  - numexpr
  - hdf5 1.8.18
  - zlib 1.2.*
  - bzip2 1.0.*  # [win]

build:
  number: {{build}}
  string: py35_{{build}}

