package: 
  name: psana-expdb
  version: "0.14"

source: 
  git_url: https://github.com/lcls-psana/psana-expdb.git 
  git_branch: master

build: 
  number: 1

requirements:
  build:
    - python
    - setuptools
