package: 
  name: toconda
  version: "0.4"

source: 
  git_url: https://github.com/lcls-psana/psana-expdb.git 
  git_tag: "v0.1" 

build: 
  number: 5

requirements:
  build:
    - python
    - setuptools
