# this is a proxy package to a locally installed version of valgrind

{% set build = 100 %}
{% set version = '3.11.0' %}
{% set pkg = 'valgrind' %}

package:
  name: {{ pkg }}
  version: {{ version }}

about:
  home: http://valgrind.org/downloads/current.html

build:
  number: {{build}}
  string: local_{{build}}
  binary_relocation: true
  detect_binary_files_with_prefix: true

  script_env:
    - REDHATVER

test:
  commands:
    - valgrind ls -l
  

