- pkg: szip
  paths: 
  - external/szip

- pkg: dbg
  paths: 
  - system/dbg
 
- pkg: gpu
  paths: 
  - system/gpu

- pkg: openmpi
  paths: 
  - system/openmpi-1.10x
  - system/openmpi-2x
  
- pkg: hdf5
  paths:
  - system/hdf5-1.8x
  - system/hdf5-1.10x
  - system/hdf5-1.10.1pre

- pkg: mpi4py
  paths:
  - system/mpi4py
  - system/mpi4py-py3

- pkg: h5py
  paths:
  - system/h5py
  - system/h5py-py3
  - system/h5py-hdf5-1.10
  - system/h5py-hdf5-1.10-py3

- pkg: pytables
  paths:
  - system/pytables
  - system/pytables-py3
  # pytables doesn't support hdf5 1.10
  
#- pkg: psana-conda
#  paths:
#  - psana/psana-conda-opt

- pkg: tensorflow
  paths:
  - external/tensorflow
  - external/tensorflow-gpu
  - external/tensorflow-py3
  limit_os: rhel7
  
- pkg: keras
  paths:
  - external/keras
  - external/keras-py3

- pkg: hexanode-proxy
  paths:
  - external/hexanode_proxy

- pkg: yaml-cpp
  paths:
  - external/yaml-cpp
  limit_os: rhel7

- pkg: kerberos
  paths:
  - external/kerberos

- pkg: logbookclient
  paths:
  - external/logbookclient

- pkg: pscache
  paths:
  - external/pscache

- pkg: psgeom
  paths:
  - external/psgeom

- pkg: psocake
  paths:
  - external/psocake

- pkg: kafka-python
  paths:
  - external/kafka-python
  - external/kafka-python-py3
