{% set build = 101 %}
{% set version = '1.10.0' %}
{% set pkg = 'hdf5' %}

package:
  name: {{ pkg }}
  version: {{ version }}

source:
  fn: /reg/g/psdm/sw/conda/downloads/otherpkgs/{{ pkg }}-{{ version }}-patch1.tar.gz
  md5: 9180ff0ef8dc2ef3f61bd37a7404f295
  patches:
    - cachesize.patch

requirements:
  build:
    - szip ==2.1
    - openmpi ==1.10.3 lsf_verbs_101

  run:
    - szip ==2.1
    - openmpi >=1.8,<2

build:
  features:
    - dbg
  number: {{ build }}
  string: openmpi_dbg_{{ build }}
  binary_relocation: true
  detect_binary_files_with_prefix: true

