package:
  name: xtcav
  version: "0.1"

source:
  git_url: https://github.com/cmeister747/xtcav.git
 # git_tag: ""
  git_rev: master

build:
  number: 1 #{{environ.get('GIT_DESCRIBE_NUMBER', 0)}}
  script:
    - pip install --no-deps --disable-pip-version-check .

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - scipy
    - pandas
    - h5py
    - scikit-learn
    - mpi4py
    - psana-conda
