package:
  name: pypkgb
  version: "0.0.1"
 
source:
  path: /reg/g/psdm/sw/conda/testing/pypkgb

#  git_rev: v0.0.1
#  git_url: https://github.com/davidslac/PyPkgB.git
 
requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pypkga
 
test:
  imports:
    - pypkgb
 
about:
  home: https://github.com/davidsch/PyPkgB
