package:
  name: xtcav2
  version: "0.3"

source:
  git_url: https://github.com/slaclab/xtcav2
  git_tag: "v0.3"

build:
  number: 1 #{{environ.get('GIT_DESCRIBE_NUMBER', 0)}}
  script:
    - pip install --no-deps --disable-pip-version-check .

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - scipy
    - h5py
    - scikit-learn
    - mpi4py
    - psana-conda
