{% set build = 1 %}

package:
  name: tensorflow
  version: "1.0.1"

build:
  number: {{build}}
  string: py{{py}}_{{build}}
  skip: True  # [win]
  skip: True  # [py26]
  entry_points:
    - tensorboard = tensorflow.tensorboard.tensorboard:main

# pip install tensorflow to see what pip puts in
requirements:
  build:
    - python ==3.5
    - pip
    - numpy >=1.11.0
    - protobuf >=3.1.0
    - wheel
    - six >=1.10.0
    - setuptools

  run:
    - python >=3.5,<4
    - numpy >=1.11.0
    - protobuf >=3.1.0
    - six >=1.10.0

test:
  requires:
  - python >=3.5,<4

  imports:
  - tensorflow

about:
  home: http://tensorflow.org/
  license: Apache 2.0
  summary: TensorFlow helps the tensors flow

