{% set build = 1 %}

package:
  name: tensorflow
  version: "0.11.0"

build:
  number: {{build}}
  string: py{{py}}_gpu_{{build}}
  skip: True  # [win]
  skip: True  # [osx]
  skip: True  # [py26]

  entry_points:
    - tensorboard = tensorflow.tensorboard.tensorboard:main

# did pip install to see what dependencies are
requirements:
  build:
    - python >=2.7,<3
    - pip
    - numpy >=1.8.2
    - mock >=2.0.0
    - protobuf ==3.0.0
    - wheel
    - six >=1.10.0
    - funcsigs >=1
    - pbr >=0.11
    - setuptools

  run:
    - python >=2.7,<3
    - numpy >=1.8.2
    - mock >=2.0.0
    - protobuf ==3.0.0
    - six >=1.10.0
    - funcsigs >=1
    - pbr >=0.11
    - cudnn ==5.1

# don't test the gpu version, need to be on a special machine

about:
  home: http://tensorflow.org/
  license: Apache 2.0
  summary: TensorFlow helps the tensors flow

