{% set pkg = 'mpi4py' %}
{% set version = '2.0.0' %}
{% set build = 104 %}

{% set mpi = 'openmpi' %}

package:
  name: {{ pkg }}
  version: {{ version }}

source:
  fn: /reg/g/psdm/sw/conda/downloads/otherpkgs/{{ pkg }}-{{ version }}.tar.gz
  md5: 4f7d8126d7367c239fd67615680990e3

requirements:
  build:
    - python >=2.7,<3
    - openmpi ==1.10.6 lsf_verbs_1

  run:
    - python >=2.7,<3
    - openmpi >=1.8,<2
    - numpy

build:
  number: {{build}}
  string: py{{py}}_{{mpi}}_{{build}}

test:
  imports:
    - mpi4py
    - mpi4py.rc
    - mpi4py.dl # [not win]
    - mpi4py.MPI
