{% set build = 1 %}

package:
  name: tensorflow
  version: "1.1.0"

build:
  number: {{build}}
  string: py{{py}}_{{build}}
  skip: True  # [win]
  skip: True  # [py26]

  entry_points:
    - tensorboard = tensorflow.tensorboard.tensorboard:main

# pip install tensorflow to see what pip puts in
requirements:
  build:
    - python >=2.7,<3
    - pip
    - numpy >=1.11.0
    - mock >=2.0.0
    - protobuf >=3.2.0
    - wheel
    - six >=1.10.0
    - funcsigs >=1
    - pbr >=0.11
    - setuptools
    - werkzeug

  run:
    - python >=2.7,<3
    - numpy >=1.11.0
    - mock >=2.0.0
    - protobuf >=3.1.0
    - six >=1.10.0
    - funcsigs >=1
    - pbr >=0.11
    - werkzeug
    
test:
  requires:
  - python >=2.7,<3

  imports:
  - tensorflow

about:
  home: http://tensorflow.org/
  license: Apache 2.0
  summary: TensorFlow helps the tensors flow

