{% set build = 4 %}
{% set version = '1.10.0' %}
{% set pkg = 'hdf5' %}

package:
  name: {{ pkg }}
  version: {{ version }}

about:
  home: https://www.hdfgroup.org/HDF5
  summary: 'hdf5 data model, library and file format for storing and managing data'
  license: 'BSD style (https://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.0/src/unpacked/COPYING)'

source:
  fn: /reg/g/psdm/sw/conda/downloads/otherpkgs/{{ pkg }}-{{ version }}-patch1.tar.gz
  md5: 9180ff0ef8dc2ef3f61bd37a7404f295
#  patches:
#    - cachesize.patch

requirements:
  build:
    - szip ==2.1
    - openmpi ==1.10.6 lsf_verbs_1

  run:
    - szip ==2.1
    - openmpi >=1.8,<2

build:
  number: {{ build }}
  string: openmpi_dbg_{{ build }}
  binary_relocation: true
  detect_binary_files_with_prefix: true

test:
  files:
    - h5_cmprss.c
  commands:
    - ls
    - pwd
    - command -v h5ls
    - command -v h5c++
    - command -v h5pcc
    - h5c++ h5_cmprss.c -o h5_cmprss
    - ./h5_cmprss
    - h5ls cmprss.h5
